### PR TITLE
#3 Fix style preprocessing with Svelte versions 3.30.0 and beyond

### LINKED ISSUE #3: PostCSS preprocessing breaks with Svelte versions 3.30.0+
If I try to define PostCSS plugins when using Svelte version `3.30.0` or later, the build crashes on few different errors, depending on the Svelte version. This error is one of them:

```
/Users/arggh/.meteor/packages/coffeescript/.1.0.17.jzhn4e.2mhnq++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

TypeError: processed.code.replace is not a function
    at parse_attached_sourcemap (/Users/arggh/Develop/app/node_modules/svelte/src/compiler/utils/mapped_code.ts:305:34)
    at processed_tag_to_code (/Users/arggh/Develop/app/node_modules/svelte/src/compiler/preprocess/index.ts:111:2)
    at process_single_tag (/Users/arggh/Develop/app/node_modules/svelte/src/compiler/preprocess/index.ts:168:10)
```

Reproduction: https://github.com/arggh/meteor-melte-version-issue/

### PR DESCRIPTION
**Pull request by arggh**
Style preprocessor's return value's property `code` should hold just the CSS string, not the full result from PostCSS. This fixed implementation works with both 3.30.0+ and earlier versions of Svelte.

Things broke when Svelte hit `3.30.0` (https://github.com/sveltejs/svelte/pull/5584), changing style preprocessor flow by introducing sourcemap support.

Fixes #3

### CODE REVIEW

**Comment by zodern** [comment]
Thanks @arggh
